<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<gazebo reference="camera_link">
		<sensor type="camera" name="camera1">
			<update_rate>
				30.0
			</update_rate>
			<camera name="head">
				<horizontal_fov>
					1.3962634
				</horizontal_fov>
				<image>
					<width>
						800
					</width>
					<height>
						800
					</height>
					<format>
						R8G8B8
					</format>
				</image>
				<clip>
					<near>
						0.02
					</near>
					<far>
						300
					</far>
				</clip>
				<noise>
					<type>
						gaussian
					</type>
					<!--
					Noise is sampled independently per pixel on each frame.
					That pixel's noise value is added to each of its color
					channels, which at that point lie in the range [0,1].
					-->
					<mean>
						0.0
					</mean>
					<stddev>
						0.007
					</stddev>
				</noise>
			</camera>
			<plugin name="camera_controller" filename="libgazebo_ros_camera.so">
				<alwaysOn>
					true
				</alwaysOn>
				<updateRate>
					0.0
				</updateRate>
				<cameraName>
					robot/camera
				</cameraName>
				<imageTopicName>
					image_raw
				</imageTopicName>
				<cameraInfoTopicName>
					camera_info
				</cameraInfoTopicName>
				<frameName>
					camera_link
				</frameName>
				<hackBaseline>
					0.07
				</hackBaseline>
				<distortionK1>
					0.0
				</distortionK1>
				<distortionK2>
					0.0
				</distortionK2>
				<distortionK3>
					0.0
				</distortionK3>
				<distortionT1>
					0.0
				</distortionT1>
				<distortionT2>
					0.0
				</distortionT2>
			</plugin>
		</sensor>
		<material>
			Gazebo/Blue
		</material>
	</gazebo>
	<gazebo>
		<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<num_wheel_pairs>
				2
			</num_wheel_pairs>
			<right_joint>
				wheel_FR_joint
			</right_joint>
			<right_joint>
				wheel_RR_joint
			</right_joint>
			<left_joint>
				wheel_FL_joint
			</left_joint>
			<left_joint>
				wheel_RL_joint
			</left_joint>
			<wheel_separation>
				${chassis_width}
			</wheel_separation>
			<wheel_separation>
				${chassis_width}
			</wheel_separation>
			<wheel_diameter>
				${wheel_radius* 2}
			</wheel_diameter>
			<wheel_diameter>
				${wheel_radius* 2}
			</wheel_diameter>
			<max_wheel_torque>
				1000
			</max_wheel_torque>
			<max_wheel_acceleration>
				5.0
			</max_wheel_acceleration>
			<publish_odom>
				true
			</publish_odom>
			<publish_odom_tf>
				true
			</publish_odom_tf>
			<publish_wheel_tf>
				true
			</publish_wheel_tf>
			<odometry_topic>
				odom
			</odometry_topic>
			<odometry_frame>
				odom
			</odometry_frame>
			<update_rate>
				20.0
			</update_rate>
			<command_topic>
				cmd_vel
			</command_topic>
			<robot_base_frame>
				base_footprint
			</robot_base_frame>
		</plugin>
	</gazebo>
	<gazebo reference="wheel_FL">
		<material>
			Gazebo/Yellow
		</material>
		<mu1>
			1.0
		</mu1>
		<mu2>
			1.0
		</mu2>
	</gazebo>
	<gazebo reference="wheel_FR">
		<material>
			Gazebo/Red
		</material>
		<mu1>
			1.0
		</mu1>
		<mu2>
			1.0
		</mu2>
	</gazebo>
	<gazebo reference="wheel_RL">
		<material>
			Gazebo/Green
		</material>
		<mu1>
			1.0
		</mu1>
		<mu2>
			1.0
		</mu2>
	</gazebo>
	<gazebo reference="wheel_RR">
		<material>
			Gazebo/Black
		</material>
		<mu1>
			1.0
		</mu1>
		<mu2>
			1.0
		</mu2>
	</gazebo>
	<gazebo reference="base_link">
		<material>
			Gazebo/Orange
		</material>
	</gazebo>



</robot>
